sudo: required

services:
  - docker

before_install:
  - docker build -t learn-go-with-tests .

script:
  - docker run --rm -it learn-go-with-tests make test
  - docker run --rm -it learn-go-with-tests make build pdf epub mobi

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _book/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master