sudo: required

services:
  - docker

before_install:
  - docker build -t learn-go-with-tests .

script:
  - docker run --rm -it learn-go-with-tests make test
  - docker run --rm -it learn-go-with-tests make publish -e GITHUB_TOKEN=$GITHUB_TOKEN